# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: ubuntu
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install pip and create necessary directories.
          command: |
            apt update && apt -y upgrade
            apt install -y python3-pip python3-venv

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt
            pip3 install -r test_requirements.txt
            pip3 install -e .
          
        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests/test_overtools.py -vvv -s
            pytest tests/test_overprint.py -vvv -s

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
