---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-test4-hs
  labels:
    app: ubuntu-test4
spec:
  clusterIP: None
  selector:
    app: ubuntu-test4
---
apiVersion: apps/v1beta1 
kind: StatefulSet
metadata:
  name: ubuntu-test4
spec:
  serviceName: ubuntu-test4-hs
  selector:
    matchLabels:
      app: ubuntu-test4
  replicas: 3 
  template: 
    metadata:
      labels:
        app: "ubuntu-test4"
        name : "ubuntu-test4"
        overscaler : "true" 
        metric-1: "cpu-usage-percent"
        metric-2: "memory-usage-percent"
        metric-3: "network-rx-rate"
        rule-1: "cpu-usage-percent_greater_00000_reduce"
        current-count : "0"
        autoscaler-count : "2"
        min-replicas : "1"
        max-replicas : "5"
        rescaling : "true"
    spec:
      containers:
      - name: ubuntu-test4
        image: ubuntu
        ports:
        command: ["/bin/sh","-c"]
        args: ["sleep infinity"]
        resources:
            limits:
              cpu: 100m
              memory: 300Mi
