---
apiVersion: v1
kind: Service
metadata:
  name: overscaler-hs
  labels:
    app: overscaler
spec:
  clusterIP: None
  selector:
    app: overscaler
---
apiVersion: apps/v1beta1 
kind: StatefulSet
metadata:
  name: overscaler
spec:
  serviceName: overscaler-hs
  selector:
    matchLabels:
      app: overscaler
  replicas: 1 
  template: 
    metadata:
      labels:
        app: "overscaler"
        name: "overscaler"
    spec:
      containers:
      - name: overscaler
        image: path/image/of/overscaler
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /overscaler/credentials/application_default_credentials.json
          - name: CLUSTER
            value: cluster_name
          - name: NAMESPACE
            value: namespace
          - name: PROJECT
            value: project
          - name: ZONE
            value: zone
          - name: REFRESH_CLUSTER
            value: seconds
          - name: REFRESH_STATEFULSET
            value: seconds
          - name: REFRESH_AUTH
            value: seconds

        command: ["/bin/sh","-c"]
        args: [
            "gcloud auth activate-service-account --key-file /overscaler/credentials/application_default_credentials.json;
             gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $PROJECT;
             python3 /overscaler/python/overscaler.py --cluster=$CLUSTER --namespace=$NAMESPACE --zone=$ZONE --project=$PROJECT --refresh_statefulset=$REFRESH_STATEFULSET --refresh_cluster=$REFRESH_CLUSTER --refresh_auth=$REFRESH_AUTH"]
        resources:
            limits:
              cpu: 100m
              memory: 300Mi
        volumeMounts:
          - name: volume_name
            mountPath: /overscaler/credentials/

      volumes:
        - name: volume_name
          secret:
            secretName: secret_name

